### PR TITLE
Add jira user pass and change Timezone format to work with jira Server

### PR DESCRIPTION
**Pull request by shayegh**
Hi,
I add some changes in regard to #10 issue, that was because of the time zone format.
please check it.

### CODE REVIEW

**Comment by simoneldevig** [comment]
@shayegh there are some different issues to be resolved before I can merge this PR.

1. Are all the things regarding http scope and auth necessary for getting the integration to work? First all I don't think we should accept http, we should only use https. The next thing is that we shouldn't store passwords in the browser storage, it's better to use the current approach where the user has to be logged into JIRA inside the browser. 
2. The gecko property should not be removed since that is what makes the extension work in Firefox.
3. The linter fails in Travis CI. These errors should be resolved before merge.

If all the things in this PR are needed for making it work with JIRA Server, I think it would be better if you just used your own fork instead of the public extension since the majority of users are using JIRA Cloud :smile:

**Comment by shayegh** [comment]
Hi,
But the most tricky part was the time zone format

**Comment by simoneldevig** [comment]
So it works if you only change the timezone stuff?

**Comment by shayegh** [comment]
> @shayegh there are some different issues to be resolved before I can merge this PR.
> 
> 1. Are all the things regarding http scope and auth necessary for getting the integration to work? First all I don't think we should accept http, we should only use https. The next thing is that we shouldn't store passwords in the browser storage, it's better to use the current approach where the user has to be logged into JIRA inside the browser.
> 2. The gecko property should not be removed since that is what makes the extension work in Firefox.
> 3. The linter fails in Travis CI. These errors should be resolved before merge.
> 
> If all the things in this PR are needed for making it work with JIRA Server, I think it would be better if you just used your own fork instead of the public extension since the majority of users are using JIRA Cloud 😄

number 2, about gecko when I add it Chrome gives some warning. 
number 1, my server doesn't have https so I must use HTTP
I changed other parts as you suggest.

**Comment by simoneldevig** [comment]
@shayegh tested out your branch and fixed minor stuff. 

The PR will be merged and I will release a new version as soon as Chrome team accepts it 👍

**Pull request merged**
